language: r

dist: bionic

# need sudo
sudo: true

# cache packages because devtools is a beast
cache: packages

# Be strict when checking our package
warnings_are_errors: true

# don't build the vignette
r_build_args: "--no-build-vignettes"
r_check_args: "--no-build-vignettes --ignore-vignettes --as-cran"

# System dependencies
#apt_packages:
# - libcurl4-openssl-dev
# - libxml2-dev

before_isntall:
  - Rscript -e 'install.packages(c("shiny","utf8","curl","openssl","git2r","rjsonio"),lib="/home/travis/R-bin/lib/R/library/")'

# Binaries from Michael Rutter's ppa
r_binary_packages:
 - magrittr
 - ggplot2
 - plyr
 - Rcpp
 - RCurl
 # - shiny
 - stringr
 - stringi
 - MASS
 - RColorBrewer
 # - utf8
 - digest
 - colorspace
 # - curl
 # - openssl
 # - git2r
 - foreach
 - iterators
 # - RJSONIO
 - yaml
 - testthat
 - rgl
 
# Done via install.packages
#r_packages:

# Install the bleeding edge version of a package from github (eg to pick
# up a not-yet-released bugfix)
r_github_packages:
 - joshuaulrich/xts
 - braverock/blotter
 - ramnathv/rCharts
 # - r-lib/covr
 
after_success:
  - travis_wait 30 Rscript -e 'covr::codecov()'
